global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using System.Reflection;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using LinkedListWorkflowEngine.Core.Common;
global using LinkedListWorkflowEngine.Core.ErrorHandling;
global using LinkedListWorkflowEngine.Core.Guards;
global using LinkedListWorkflowEngine.Core.Interfaces;
global using LinkedListWorkflowEngine.Core.Models;
global using ExecutionContext = LinkedListWorkflowEngine.Core.Models.ExecutionContext;
global using LinkedListWorkflowEngine.Core.Persistence;
