global using System.Collections.Concurrent;
global using Microsoft.Extensions.Logging;
global using LinkedListWorkflowEngine.Core;
global using LinkedListWorkflowEngine.Core.ErrorHandling;
global using LinkedListWorkflowEngine.Core.Interfaces;
global using LinkedListWorkflowEngine.Core.Models;
global using LinkedListWorkflowEngine.Core.Persistence;
global using Moq;
global using Xunit;
